### ISSUE TITLE
Feature Request: Lightspeed Ecom

### ISSUE THREAD

**Issue by bramski** [digitaport/lightspeed-sdk#6]
Hello Lightspeed SDK,

This looks like the best library for working with lightspeed API via Node. I have a need to utilize the ecom REST API. I will do this work regardless. Are you interested in my contribution to this project of the ecom portions?  I would likely diverge it from the lightspeed API portion and make a separate named export for the ecom API.

**Comment by jcperez** [comment]
Sure! Your contribution will be highly appreciated! Please send any changes via Pull Request and we can manage the publication of new versions of the module.

**Comment by bramski** [comment]
Implemented by: https://github.com/digitaport/lightspeed-sdk/pull/8
